In [1]:
import pandas as pd

In [5]:
speeds = pd.DataFrame(
    [
    ("bird", "Falconiformes", 389.0),
    ("bird", "Psittaciformes", 24.0),
    ("mammal", "Carnivora", 80.2),
    ("mammal", "Primates", 70.7),
    ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)
speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates       70.7
leopard  mammal       Carnivora       58.0

In [7]:
grouped = speeds.groupby("class")
grouped

In [8]:
grouped = speeds.groupby(["class", "order"])
grouped

In [20]:
speeds.groupby(["order"]).count()

                class  max_speed
order
Carnivora           2          2
Falconiformes       1          1
Primates            1          1
Psittaciformes      1          1

In [21]:
speeds.groupby(["order"]).max()

                 class  max_speed
order
Carnivora       mammal       80.2
Falconiformes     bird      389.0
Primates        mammal       70.7
Psittaciformes    bird       24.0